fix type error
nk2028/opencc-js pull request #18
Opened 2021-12-04 17:28 UTC by Aqzhyi

```
webpack-internal:///./node_modules/opencc-js/bundle-node.js:97
      const n = s.length, arr = [];
                  ^

TypeError: Cannot read properties of undefined (reading 'length')
    at Trie.convert (webpack-internal:///./node_modules/opencc-js/bundle-node.js:97:19)
    at convert (webpack-internal:///./node_modules/opencc-js/bundle-node.js:170:48)
    at pushRssToChannel (webpack-internal:///./src/news/pushRssToChannel.ts:31:39)
    at eval (webpack-internal:///./src/bot/botStart.ts:51:52)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[nodemon] app crashed - waiting for file changes before starting...
```

2021-12-04 18:35 UTC, ayaka14732 requested changes
`s` is expected to be a string. For this issue, we should fix the caller instead of modifying this function

2021-12-27 02:50 UTC, Aqzhyi commented
> `s` is expected to be a string. For this issue, we should fix the caller instead of modifying this function

Hi, greetings, what do you mean? Which caller?

Do you mean I should fix it on my application itself and not this package?

I tried several ways but I can't fix it unless modifying this package.

```
import * as OpenCC from 'opencc-js'

export const toTW = OpenCC.Converter({ from: 'cn', to: 'tw' })
```

It builds ok, but broke after running `npm start`

Or maybe, what is your suggestions for updating the pull request?

2021-12-27 03:04 UTC, ayaka14732 commented
Hi, @Aqzhyi. I have just checked and I can run your code without any errors.

```javascript
import * as OpenCC from 'opencc-js';
const toTW = OpenCC.Converter({ from: 'cn', to: 'tw' });
console.log(toTW('吃面'));  // 吃麵
```

2021-12-27 06:00 UTC, Aqzhyi commented
ok, thank you many thanks, let me do more trials.

failed on Linode and netlify. but local looks working.

![screenshot-xKae9cWU](https://user-images.githubusercontent.com/1500206/147439440-342ce7e8-47e7-4a79-9032-01f3d0301af0.png)

2026-05-01 11:52 UTC, frankslin commented
Thanks for the PR, and sorry this stayed open for so long.

I took another look at this against the current code. I don't think this is the right fix for `opencc-js`: the converter API expects the input to be a string, and the public types now make that contract explicit as `(text: string) => string`. If `undefined` reaches `Trie.convert`, that means the caller passed a missing or invalid value. Returning an empty string in that case would hide that data bug and could silently drop content.

I also verified that the normal usage path works as expected:

```js
import OpenCC from 'opencc-js';

const c = OpenCC.Converter({ from: 'cn', to: 'tw' });
console.log(c('吃面')); // 吃麵
```

For applications that may receive optional values, the safer fix is to normalize or validate at the call site, for example only calling the converter when the value is a string.

I am going to close this PR, but thank you again for reporting the issue and proposing a patch.

2026-05-01 11:52 UTC, closed without merging